apiVersion: v1
kind: Service
metadata:
  name: s2s-agent
  namespace: elm-s2s
  labels:
    app: s2s-agent
spec:
  type: ClusterIP
  selector:
    app: s2s-agent
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
    - name: health
      port: 8081
      targetPort: 8081
      protocol: TCP
